Repository umami-hep/puma, pull requests merged in 2025-06, with the labels that each got.

#319 Enable Storage of Histogram/ROC Objects
  changelog.md
  examples/high_level_plots.py
  examples/plot_basic_histogram.py
  examples/plot_data_mc.py
  examples/plot_discriminant_scores.py
  examples/plot_flavour_probabilities.py
  examples/plot_histogram_underoverflow.py
  examples/plot_histograms_from_files.py
  examples/plot_rocs.py
  examples/plot_weighted_histograms.py
  examples/plt_cfg.yaml
  examples/plt_cfg_xbb.yaml
  puma/histogram.py
  puma/hlplots/aux_results.py
  puma/hlplots/results.py
  puma/hlplots/tagger.py
  puma/plot_base.py
  puma/roc.py
  puma/tests/expected_plots/test_flavoured_labels.png
  puma/tests/expected_plots/test_histogram_custom_range.png
  puma/tests/expected_plots/test_histogram_different_ranges.png
  puma/tests/expected_plots/test_histogram_empty_reference_no_norm.png
  puma/tests/expected_plots/test_histogram_empty_reference_norm.png
  puma/tests/expected_plots/test_histogram_ratio_value.png
  puma/tests/expected_plots/test_histogram_ratio_value_transparent.png
  puma/tests/expected_plots/test_ratio_groups.png
  puma/tests/hlplots/test_aux_results.py
  puma/tests/hlplots/test_results.py
  puma/tests/test_histogram.py
  puma/tests/test_plot_base.py
Labels: No backward compatability

#323 Adding option to define the plot layout
  changelog.md
  puma/plot_base.py
  puma/tests/expected_plots/test_draw_vlines_histogram.png
  puma/tests/expected_plots/test_draw_vlines_histogram_custom_labels.png
  puma/tests/expected_plots/test_draw_vlines_histogram_custom_yheight.png
  puma/tests/expected_plots/test_draw_vlines_histogram_same_height.png
  puma/tests/expected_plots/test_filled_histogram.png
  puma/tests/expected_plots/test_flavoured_labels.png
  puma/tests/expected_plots/test_histogram_data_mc.png
  puma/tests/expected_plots/test_histogram_different_ranges.png
  puma/tests/expected_plots/test_histogram_discrete_values.png
  puma/tests/expected_plots/test_histogram_empty_reference_no_norm.png
  puma/tests/expected_plots/test_histogram_empty_reference_norm.png
  puma/tests/expected_plots/test_histogram_ratio_value.png
  puma/tests/expected_plots/test_histogram_ratio_value_transparent.png
  puma/tests/expected_plots/test_histogram_with_underoverflow_bins.png
  puma/tests/expected_plots/test_histogram_without_underoverflow_bins.png
  puma/tests/expected_plots/test_int_eff_one_tagger.png
  puma/tests/expected_plots/test_int_eff_two_taggers.png
  puma/tests/expected_plots/test_ratio_groups.png
  puma/tests/expected_plots/test_vtx_fake_rate.png
  puma/tests/hlplots/expected_plots/bjets_all_samples.png
  puma/tests/hlplots/expected_plots/cjets_all_samples.png
  puma/tests/hlplots/expected_plots/extra_kwargs_bjets_all_samples.png
  puma/tests/hlplots/expected_plots/extra_kwargs_cjets_all_samples.png
  puma/tests/hlplots/expected_plots/extra_kwargs_ujets_all_samples.png
  puma/tests/hlplots/expected_plots/ujets_all_samples.png
  puma/tests/hlplots/test_n_track_origin.py
  puma/tests/utils/expected_plots/test_linestyles.png
Labels: enhancement

#328 Puma Tutorial Fixes
  changelog.md
  docs/examples/tutorial-plotting.md
Labels: documentation
